//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public struct ServerDefs_InviteCode: Codable, Hashable, Sendable {
        public var available: Int
        public var code: String
        public var createdAt: String
        public var createdBy: String
        public var disabled: Bool
        public var forAccount: String
        public var uses: [ServerDefs_InviteCodeUse]
        public let _unknownValues: [String: AnyCodable]

        public init(available: Int, code: String, createdAt: String, createdBy: String, disabled: Bool, forAccount: String, uses: [ServerDefs_InviteCodeUse]) {
            self.available = available
            self.code = code
            self.createdAt = createdAt
            self.createdBy = createdBy
            self.disabled = disabled
            self.forAccount = forAccount
            self.uses = uses
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case available
            case code
            case createdAt
            case createdBy
            case disabled
            case forAccount
            case uses
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.available = try keyedContainer.decode(Int.self, forKey: .available)
            self.code = try keyedContainer.decode(String.self, forKey: .code)
            self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
            self.createdBy = try keyedContainer.decode(String.self, forKey: .createdBy)
            self.disabled = try keyedContainer.decode(Bool.self, forKey: .disabled)
            self.forAccount = try keyedContainer.decode(String.self, forKey: .forAccount)
            self.uses = try keyedContainer.decode([ServerDefs_InviteCodeUse].self, forKey: .uses)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.available, forKey: .available)
            try container.encode(self.code, forKey: .code)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.createdBy, forKey: .createdBy)
            try container.encode(self.disabled, forKey: .disabled)
            try container.encode(self.forAccount, forKey: .forAccount)
            try container.encode(self.uses, forKey: .uses)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerDefs_InviteCodeUse: Codable, Hashable, Sendable {
        public var usedAt: String
        public var usedBy: String
        public let _unknownValues: [String: AnyCodable]

        public init(usedAt: String, usedBy: String) {
            self.usedAt = usedAt
            self.usedBy = usedBy
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case usedAt
            case usedBy
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.usedAt = try keyedContainer.decode(String.self, forKey: .usedAt)
            self.usedBy = try keyedContainer.decode(String.self, forKey: .usedBy)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.usedAt, forKey: .usedAt)
            try container.encode(self.usedBy, forKey: .usedBy)
            try _unknownValues.encode(to: encoder)
        }
    }
}
