//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum IdentityResolveHandle {
      public static let id = "com.atproto.identity.resolveHandle"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var handle: String

              public init(handle: String) {
                self.handle = handle
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.IdentityResolveHandle_Output)
                        public var json: comatprototypes.IdentityResolveHandle_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case handlenotfound(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "HandleNotFound":
                  self = .handlenotfound(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .handlenotfound:
                  return "HandleNotFound"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .handlenotfound(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct IdentityResolveHandle_Output: Codable, Hashable, Sendable {
        public var did: String
        public let _unknownValues: [String: AnyCodable]

        public init(did: String) {
            self.did = did
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.did, forKey: .did)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `IdentityResolveHandle.Error` instead.")
    public typealias IdentityResolveHandle_Error = IdentityResolveHandle.Error
}
