//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum SyncListRepos {
      public static let id = "com.atproto.sync.listRepos"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var cursor: String?
              public var limit: Int?

              public init(cursor: String? = nil, limit: Int? = nil) {
                self.cursor = cursor
                self.limit = limit
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.SyncListRepos_Output)
                        public var json: comatprototypes.SyncListRepos_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct SyncListRepos_Output: Codable, Hashable, Sendable {
        public var cursor: String?
        public var repos: [SyncListRepos_Repo]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, repos: [SyncListRepos_Repo]) {
            self.cursor = cursor
            self.repos = repos
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case repos
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.repos = try keyedContainer.decode([SyncListRepos_Repo].self, forKey: .repos)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.repos, forKey: .repos)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct SyncListRepos_Repo: Codable, Hashable, Sendable {
        public var active: Bool?
        public var did: String
        public var head: String
        public var rev: String
        public var status: SyncListRepos_Repo_Status?
        public let _unknownValues: [String: AnyCodable]

        public init(active: Bool? = nil, did: String, head: String, rev: String, status: SyncListRepos_Repo_Status? = nil) {
            self.active = active
            self.did = did
            self.head = head
            self.rev = rev
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case head
            case rev
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.active = try keyedContainer.decodeIfPresent(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.head = try keyedContainer.decode(String.self, forKey: .head)
            self.rev = try keyedContainer.decode(String.self, forKey: .rev)
            self.status = try keyedContainer.decodeIfPresent(SyncListRepos_Repo_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encode(self.head, forKey: .head)
            try container.encode(self.rev, forKey: .rev)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum SyncListRepos_Repo_Status: RawRepresentable, Codable, Hashable, Sendable {
        case takendown
        case suspended
        case deleted
        case deactivated
        case desynchronized
        case throttled
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deleted":
                self = .deleted
            case "deactivated":
                self = .deactivated
            case "desynchronized":
                self = .desynchronized
            case "throttled":
                self = .throttled
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deleted:
                "deleted"
            case .deactivated:
                "deactivated"
            case .desynchronized:
                "desynchronized"
            case .throttled:
                "throttled"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `SyncListRepos.Error` instead.")
    public typealias SyncListRepos_Error = SyncListRepos.Error
}
