//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum AdminGetSubjectStatus {
      public static let id = "com.atproto.admin.getSubjectStatus"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var blob: String?
              public var did: String?
              public var uri: String?

              public init(blob: String? = nil, did: String? = nil, uri: String? = nil) {
                self.blob = blob
                self.did = did
                self.uri = uri
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.AdminGetSubjectStatus_Output)
                        public var json: comatprototypes.AdminGetSubjectStatus_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct AdminGetSubjectStatus_Output: Codable, Hashable, Sendable {
        public var deactivated: AdminDefs_StatusAttr?
        public var subject: AdminGetSubjectStatus_Output_Subject
        public var takedown: AdminDefs_StatusAttr?
        public let _unknownValues: [String: AnyCodable]

        public init(deactivated: AdminDefs_StatusAttr? = nil, subject: AdminGetSubjectStatus_Output_Subject, takedown: AdminDefs_StatusAttr? = nil) {
            self.deactivated = deactivated
            self.subject = subject
            self.takedown = takedown
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case deactivated
            case subject
            case takedown
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.deactivated = try keyedContainer.decodeIfPresent(AdminDefs_StatusAttr.self, forKey: .deactivated)
            self.subject = try keyedContainer.decode(AdminGetSubjectStatus_Output_Subject.self, forKey: .subject)
            self.takedown = try keyedContainer.decodeIfPresent(AdminDefs_StatusAttr.self, forKey: .takedown)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.deactivated, forKey: .deactivated)
            try container.encode(self.subject, forKey: .subject)
            try container.encodeIfPresent(self.takedown, forKey: .takedown)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum AdminGetSubjectStatus_Output_Subject: Codable, Hashable, Sendable {
        case adminDefsRepoRef(AdminDefs_RepoRef)
        case repoStrongRef(RepoStrongRef)
        case adminDefsRepoBlobRef(AdminDefs_RepoBlobRef)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.admin.defs#repoRef":
                self = try .adminDefsRepoRef(.init(from: decoder))
            case "com.atproto.repo.strongRef":
                self = try .repoStrongRef(.init(from: decoder))
            case "com.atproto.admin.defs#repoBlobRef":
                self = try .adminDefsRepoBlobRef(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .adminDefsRepoRef(value):
                try container.encode("com.atproto.admin.defs#repoRef", forKey: .type)
                try value.encode(to: encoder)
            case let .repoStrongRef(value):
                try container.encode("com.atproto.repo.strongRef", forKey: .type)
                try value.encode(to: encoder)
            case let .adminDefsRepoBlobRef(value):
                try container.encode("com.atproto.admin.defs#repoBlobRef", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    @available(*, deprecated, message: "Use `AdminGetSubjectStatus.Error` instead.")
    public typealias AdminGetSubjectStatus_Error = AdminGetSubjectStatus.Error
}
