//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum RepoImportRepo {
      public static let id = "com.atproto.repo.importRepo"
      public struct Input: Sendable, Hashable {
        public struct Headers: Sendable, Hashable {
          public var accept: [OpenAPIRuntime.AcceptHeaderContentType<RepoImportRepo.AcceptableContentType>]
          public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<RepoImportRepo.AcceptableContentType>] = .defaultValues()) {
            self.accept = accept
          }
        }
        public var headers: RepoImportRepo.Input.Headers

        @frozen public enum Body: Sendable, Hashable {
          case binary(HTTPBody)
        }
        public var body: RepoImportRepo.Input.Body

        public init(
          headers: RepoImportRepo.Input.Headers,
          body: RepoImportRepo.Input.Body
        ) {
          self.headers = headers
          self.body = body
        }
      }
      @frozen public enum Output: Sendable, Hashable {
        public struct Ok: Sendable, Hashable {
          @frozen public enum Body: Sendable, Hashable {
            case json(Swift.Bool)
            public var json: Swift.Bool {
              get throws {
                switch self {
                case .json(let body):
                  return body
                }
              }
            }
          }

          public var body: RepoImportRepo.Output.Ok.Body

          public init(body: RepoImportRepo.Output.Ok.Body) {
            self.body = body
          }
        }

        case ok(RepoImportRepo.Output.Ok)

        public var ok: RepoImportRepo.Output.Ok {
          get throws {
            switch self {
            case .ok(let response):
              return response
            default:
              try throwUnexpectedResponseStatus(
                expectedStatus: "ok",
                response: self
              )
            }
          }
        }
        case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
        case json
        case other(Swift.String)
        public init?(rawValue: Swift.String) {
          switch rawValue.lowercased() {
          case "application/json":
            self = .json
          default:
            self = .other(rawValue)
          }
        }
        public var rawValue: Swift.String {
          switch self {
          case .other(let string):
            return string
          case .json:
            return "application/json"
          }
        }
        public static var allCases: [Self] {
          [
            .json
          ]
        }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    @available(*, deprecated, message: "Use `RepoImportRepo.Error` instead.")
    public typealias RepoImportRepo_Error = RepoImportRepo.Error
}
