//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum RepoApplyWrites {
      public static let id = "com.atproto.repo.applyWrites"
      public struct Input: Sendable, Hashable {
        public struct Headers: Sendable, Hashable {
          public var accept: [OpenAPIRuntime.AcceptHeaderContentType<RepoApplyWrites.AcceptableContentType>]
          public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<RepoApplyWrites.AcceptableContentType>] = .defaultValues()) {
            self.accept = accept
          }
        }
        public var headers: RepoApplyWrites.Input.Headers

        @frozen public enum Body: Sendable, Hashable {
          case json(RepoApplyWrites_Input)
        }
        public var body: RepoApplyWrites.Input.Body

        public init(
          headers: RepoApplyWrites.Input.Headers,
          body: RepoApplyWrites.Input.Body
        ) {
          self.headers = headers
          self.body = body
        }
      }
      @frozen public enum Output: Sendable, Hashable {
        public struct Ok: Sendable, Hashable {
          @frozen public enum Body: Sendable, Hashable {
            case json(Swift.Bool)
            public var json: Swift.Bool {
              get throws {
                switch self {
                case .json(let body):
                  return body
                }
              }
            }
          }

          public var body: RepoApplyWrites.Output.Ok.Body

          public init(body: RepoApplyWrites.Output.Ok.Body) {
            self.body = body
          }
        }

        case ok(RepoApplyWrites.Output.Ok)

        public var ok: RepoApplyWrites.Output.Ok {
          get throws {
            switch self {
            case .ok(let response):
              return response
            default:
              try throwUnexpectedResponseStatus(
                expectedStatus: "ok",
                response: self
              )
            }
          }
        }
        case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
        case json
        case other(Swift.String)
        public init?(rawValue: Swift.String) {
          switch rawValue.lowercased() {
          case "application/json":
            self = .json
          default:
            self = .other(rawValue)
          }
        }
        public var rawValue: Swift.String {
          switch self {
          case .other(let string):
            return string
          case .json:
            return "application/json"
          }
        }
        public static var allCases: [Self] {
          [
            .json
          ]
        }
      }
      public indirect enum Error: XRPCError {
          case invalidswap(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "InvalidSwap":
                  self = .invalidswap(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .invalidswap:
                  return "InvalidSwap"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .invalidswap(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct RepoApplyWrites_Create: Codable, Hashable, Sendable {
        public var collection: String
        public var rkey: String?
        public var value: UnknownATPValue
        public let _unknownValues: [String: AnyCodable]

        public init(collection: String, rkey: String? = nil, value: UnknownATPValue) {
            self.collection = collection
            self.rkey = rkey
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case rkey
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collection = try keyedContainer.decode(String.self, forKey: .collection)
            self.rkey = try keyedContainer.decodeIfPresent(String.self, forKey: .rkey)
            self.value = try keyedContainer.decode(UnknownATPValue.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collection, forKey: .collection)
            try container.encodeIfPresent(self.rkey, forKey: .rkey)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoApplyWrites_CreateResult: Codable, Hashable, Sendable {
        public var cid: String
        public var uri: String
        public var validationStatus: RepoApplyWrites_CreateResult_ValidationStatus?
        public let _unknownValues: [String: AnyCodable]

        public init(cid: String, uri: String, validationStatus: RepoApplyWrites_CreateResult_ValidationStatus? = nil) {
            self.cid = cid
            self.uri = uri
            self.validationStatus = validationStatus
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
            case validationStatus
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.validationStatus = try keyedContainer.decodeIfPresent(RepoApplyWrites_CreateResult_ValidationStatus.self, forKey: .validationStatus)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.uri, forKey: .uri)
            try container.encodeIfPresent(self.validationStatus, forKey: .validationStatus)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoApplyWrites_CreateResult_ValidationStatus: RawRepresentable, Codable, Hashable, Sendable {
        case valid
        case unknown
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "valid":
                self = .valid
            case "unknown":
                self = .unknown
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .valid:
                "valid"
            case .unknown:
                "unknown"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public struct RepoApplyWrites_Delete: Codable, Hashable, Sendable {
        public var collection: String
        public var rkey: String
        public let _unknownValues: [String: AnyCodable]

        public init(collection: String, rkey: String) {
            self.collection = collection
            self.rkey = rkey
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case rkey
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collection = try keyedContainer.decode(String.self, forKey: .collection)
            self.rkey = try keyedContainer.decode(String.self, forKey: .rkey)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collection, forKey: .collection)
            try container.encode(self.rkey, forKey: .rkey)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoApplyWrites_DeleteResult: Codable, Hashable, Sendable {
        public let _unknownValues: [String: AnyCodable]

        public init() {
            self._unknownValues = [:]
        }

        public init(from decoder: any Decoder) throws {
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoApplyWrites_Input: Codable, Hashable, Sendable {
        public var repo: String
        public var swapCommit: String?
        public var validate: Bool?
        public var writes: [RepoApplyWrites_Input_Writes_Elem]
        public let _unknownValues: [String: AnyCodable]

        public init(repo: String, swapCommit: String? = nil, validate: Bool? = nil, writes: [RepoApplyWrites_Input_Writes_Elem]) {
            self.repo = repo
            self.swapCommit = swapCommit
            self.validate = validate
            self.writes = writes
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case repo
            case swapCommit
            case validate
            case writes
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.repo = try keyedContainer.decode(String.self, forKey: .repo)
            self.swapCommit = try keyedContainer.decodeIfPresent(String.self, forKey: .swapCommit)
            self.validate = try keyedContainer.decodeIfPresent(Bool.self, forKey: .validate)
            self.writes = try keyedContainer.decode([RepoApplyWrites_Input_Writes_Elem].self, forKey: .writes)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.repo, forKey: .repo)
            try container.encodeIfPresent(self.swapCommit, forKey: .swapCommit)
            try container.encodeIfPresent(self.validate, forKey: .validate)
            try container.encode(self.writes, forKey: .writes)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoApplyWrites_Input_Writes_Elem: Codable, Hashable, Sendable {
        case repoApplyWritesCreate(RepoApplyWrites_Create)
        case repoApplyWritesUpdate(RepoApplyWrites_Update)
        case repoApplyWritesDelete(RepoApplyWrites_Delete)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.repo.applyWrites#create":
                self = try .repoApplyWritesCreate(.init(from: decoder))
            case "com.atproto.repo.applyWrites#update":
                self = try .repoApplyWritesUpdate(.init(from: decoder))
            case "com.atproto.repo.applyWrites#delete":
                self = try .repoApplyWritesDelete(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .repoApplyWritesCreate(value):
                try container.encode("com.atproto.repo.applyWrites#create", forKey: .type)
                try value.encode(to: encoder)
            case let .repoApplyWritesUpdate(value):
                try container.encode("com.atproto.repo.applyWrites#update", forKey: .type)
                try value.encode(to: encoder)
            case let .repoApplyWritesDelete(value):
                try container.encode("com.atproto.repo.applyWrites#delete", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public struct RepoApplyWrites_Output: Codable, Hashable, Sendable {
        public var commit: RepoDefs_CommitMeta?
        public var results: [RepoApplyWrites_Output_Results_Elem]?
        public let _unknownValues: [String: AnyCodable]

        public init(commit: RepoDefs_CommitMeta? = nil, results: [RepoApplyWrites_Output_Results_Elem]? = nil) {
            self.commit = commit
            self.results = results
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case commit
            case results
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.commit = try keyedContainer.decodeIfPresent(RepoDefs_CommitMeta.self, forKey: .commit)
            self.results = try keyedContainer.decodeIfPresent([RepoApplyWrites_Output_Results_Elem].self, forKey: .results)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.commit, forKey: .commit)
            try container.encodeIfPresent(self.results, forKey: .results)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoApplyWrites_Output_Results_Elem: Codable, Hashable, Sendable {
        case repoApplyWritesCreateResult(RepoApplyWrites_CreateResult)
        case repoApplyWritesUpdateResult(RepoApplyWrites_UpdateResult)
        case repoApplyWritesDeleteResult(RepoApplyWrites_DeleteResult)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.repo.applyWrites#createResult":
                self = try .repoApplyWritesCreateResult(.init(from: decoder))
            case "com.atproto.repo.applyWrites#updateResult":
                self = try .repoApplyWritesUpdateResult(.init(from: decoder))
            case "com.atproto.repo.applyWrites#deleteResult":
                self = try .repoApplyWritesDeleteResult(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .repoApplyWritesCreateResult(value):
                try container.encode("com.atproto.repo.applyWrites#createResult", forKey: .type)
                try value.encode(to: encoder)
            case let .repoApplyWritesUpdateResult(value):
                try container.encode("com.atproto.repo.applyWrites#updateResult", forKey: .type)
                try value.encode(to: encoder)
            case let .repoApplyWritesDeleteResult(value):
                try container.encode("com.atproto.repo.applyWrites#deleteResult", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public struct RepoApplyWrites_Update: Codable, Hashable, Sendable {
        public var collection: String
        public var rkey: String
        public var value: UnknownATPValue
        public let _unknownValues: [String: AnyCodable]

        public init(collection: String, rkey: String, value: UnknownATPValue) {
            self.collection = collection
            self.rkey = rkey
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case rkey
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.collection = try keyedContainer.decode(String.self, forKey: .collection)
            self.rkey = try keyedContainer.decode(String.self, forKey: .rkey)
            self.value = try keyedContainer.decode(UnknownATPValue.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.collection, forKey: .collection)
            try container.encode(self.rkey, forKey: .rkey)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RepoApplyWrites_UpdateResult: Codable, Hashable, Sendable {
        public var cid: String
        public var uri: String
        public var validationStatus: RepoApplyWrites_UpdateResult_ValidationStatus?
        public let _unknownValues: [String: AnyCodable]

        public init(cid: String, uri: String, validationStatus: RepoApplyWrites_UpdateResult_ValidationStatus? = nil) {
            self.cid = cid
            self.uri = uri
            self.validationStatus = validationStatus
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
            case validationStatus
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.validationStatus = try keyedContainer.decodeIfPresent(RepoApplyWrites_UpdateResult_ValidationStatus.self, forKey: .validationStatus)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.uri, forKey: .uri)
            try container.encodeIfPresent(self.validationStatus, forKey: .validationStatus)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RepoApplyWrites_UpdateResult_ValidationStatus: RawRepresentable, Codable, Hashable, Sendable {
        case valid
        case unknown
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "valid":
                self = .valid
            case "unknown":
                self = .unknown
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .valid:
                "valid"
            case .unknown:
                "unknown"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `RepoApplyWrites.Error` instead.")
    public typealias RepoApplyWrites_Error = RepoApplyWrites.Error
}
