//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum IdentityResolveIdentity {
      public static let id = "com.atproto.identity.resolveIdentity"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var identifier: String

              public init(identifier: String) {
                self.identifier = identifier
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.IdentityDefs_IdentityInfo)
                        public var json: comatprototypes.IdentityDefs_IdentityInfo {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case diddeactivated(String?)
          case didnotfound(String?)
          case handlenotfound(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "HandleNotFound":
                  self = .handlenotfound(error.message)
              case "DidNotFound":
                  self = .didnotfound(error.message)
              case "DidDeactivated":
                  self = .diddeactivated(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .handlenotfound:
                  return "HandleNotFound"
              case .didnotfound:
                  return "DidNotFound"
              case .diddeactivated:
                  return "DidDeactivated"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .handlenotfound(message):
                  return message
              case let .didnotfound(message):
                  return message
              case let .diddeactivated(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    @available(*, deprecated, message: "Use `IdentityResolveIdentity.Error` instead.")
    public typealias IdentityResolveIdentity_Error = IdentityResolveIdentity.Error
}
