//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public indirect enum SyncDefs_HostStatus: RawRepresentable, Codable, Hashable, Sendable {
        case active
        case idle
        case offline
        case throttled
        case banned
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "active":
                self = .active
            case "idle":
                self = .idle
            case "offline":
                self = .offline
            case "throttled":
                self = .throttled
            case "banned":
                self = .banned
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .active:
                "active"
            case .idle:
                "idle"
            case .offline:
                "offline"
            case .throttled:
                "throttled"
            case .banned:
                "banned"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }
}
