//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum TempFetchLabels {
      public static let id = "com.atproto.temp.fetchLabels"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var limit: Int?
              public var since: Int?

              public init(limit: Int? = nil, since: Int? = nil) {
                self.limit = limit
                self.since = since
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.TempFetchLabels_Output)
                        public var json: comatprototypes.TempFetchLabels_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct TempFetchLabels_Output: Codable, Hashable, Sendable {
        public var labels: [LabelDefs_Label]
        public let _unknownValues: [String: AnyCodable]

        public init(labels: [LabelDefs_Label]) {
            self.labels = labels
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case labels
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.labels = try keyedContainer.decode([LabelDefs_Label].self, forKey: .labels)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.labels, forKey: .labels)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `TempFetchLabels.Error` instead.")
    public typealias TempFetchLabels_Error = TempFetchLabels.Error
}
