//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum ServerDescribeServer {
      public static let id = "com.atproto.server.describeServer"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {

              public init() {
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(comatprototypes.ServerDescribeServer_Output)
                        public var json: comatprototypes.ServerDescribeServer_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct ServerDescribeServer_Contact: Codable, Hashable, Sendable {
        public var email: String?
        public let _unknownValues: [String: AnyCodable]

        public init(email: String? = nil) {
            self.email = email
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case email
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.email = try keyedContainer.decodeIfPresent(String.self, forKey: .email)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.email, forKey: .email)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerDescribeServer_Links: Codable, Hashable, Sendable {
        public var privacyPolicy: String?
        public var termsOfService: String?
        public let _unknownValues: [String: AnyCodable]

        public init(privacyPolicy: String? = nil, termsOfService: String? = nil) {
            self.privacyPolicy = privacyPolicy
            self.termsOfService = termsOfService
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case privacyPolicy
            case termsOfService
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.privacyPolicy = try keyedContainer.decodeIfPresent(String.self, forKey: .privacyPolicy)
            self.termsOfService = try keyedContainer.decodeIfPresent(String.self, forKey: .termsOfService)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.privacyPolicy, forKey: .privacyPolicy)
            try container.encodeIfPresent(self.termsOfService, forKey: .termsOfService)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct ServerDescribeServer_Output: Codable, Hashable, Sendable {
        public var availableUserDomains: [String]
        public var contact: ServerDescribeServer_Contact?
        public var did: String
        public var inviteCodeRequired: Bool?
        public var links: ServerDescribeServer_Links?
        public var phoneVerificationRequired: Bool?
        public let _unknownValues: [String: AnyCodable]

        public init(availableUserDomains: [String], contact: ServerDescribeServer_Contact? = nil, did: String, inviteCodeRequired: Bool? = nil, links: ServerDescribeServer_Links? = nil, phoneVerificationRequired: Bool? = nil) {
            self.availableUserDomains = availableUserDomains
            self.contact = contact
            self.did = did
            self.inviteCodeRequired = inviteCodeRequired
            self.links = links
            self.phoneVerificationRequired = phoneVerificationRequired
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case availableUserDomains
            case contact
            case did
            case inviteCodeRequired
            case links
            case phoneVerificationRequired
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.availableUserDomains = try keyedContainer.decode([String].self, forKey: .availableUserDomains)
            self.contact = try keyedContainer.decodeIfPresent(ServerDescribeServer_Contact.self, forKey: .contact)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.inviteCodeRequired = try keyedContainer.decodeIfPresent(Bool.self, forKey: .inviteCodeRequired)
            self.links = try keyedContainer.decodeIfPresent(ServerDescribeServer_Links.self, forKey: .links)
            self.phoneVerificationRequired = try keyedContainer.decodeIfPresent(Bool.self, forKey: .phoneVerificationRequired)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.availableUserDomains, forKey: .availableUserDomains)
            try container.encodeIfPresent(self.contact, forKey: .contact)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.inviteCodeRequired, forKey: .inviteCodeRequired)
            try container.encodeIfPresent(self.links, forKey: .links)
            try container.encodeIfPresent(self.phoneVerificationRequired, forKey: .phoneVerificationRequired)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `ServerDescribeServer.Error` instead.")
    public typealias ServerDescribeServer_Error = ServerDescribeServer.Error
}
