//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum SyncGetBlocks {
      public static let id = "com.atproto.sync.getBlocks"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var cids: [String]
              public var did: String

              public init(cids: [String], did: String) {
                self.cids = cids
                self.did = did
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(Data)
                        public var json: Data {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case blocknotfound(String?)
          case repodeactivated(String?)
          case reponotfound(String?)
          case reposuspended(String?)
          case repotakendown(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "BlockNotFound":
                  self = .blocknotfound(error.message)
              case "RepoNotFound":
                  self = .reponotfound(error.message)
              case "RepoTakendown":
                  self = .repotakendown(error.message)
              case "RepoSuspended":
                  self = .reposuspended(error.message)
              case "RepoDeactivated":
                  self = .repodeactivated(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .blocknotfound:
                  return "BlockNotFound"
              case .reponotfound:
                  return "RepoNotFound"
              case .repotakendown:
                  return "RepoTakendown"
              case .reposuspended:
                  return "RepoSuspended"
              case .repodeactivated:
                  return "RepoDeactivated"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .blocknotfound(message):
                  return message
              case let .reponotfound(message):
                  return message
              case let .repotakendown(message):
                  return message
              case let .reposuspended(message):
                  return message
              case let .repodeactivated(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    @available(*, deprecated, message: "Use `SyncGetBlocks.Error` instead.")
    public typealias SyncGetBlocks_Error = SyncGetBlocks.Error
}
