//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public struct RepoDefs_CommitMeta: Codable, Hashable, Sendable {
        public var cid: String
        public var rev: String
        public let _unknownValues: [String: AnyCodable]

        public init(cid: String, rev: String) {
            self.cid = cid
            self.rev = rev
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case rev
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.rev = try keyedContainer.decode(String.self, forKey: .rev)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.rev, forKey: .rev)
            try _unknownValues.encode(to: encoder)
        }
    }
}
