//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension comatprototypes {
    public enum ServerRefreshSession {
      public static let id = "com.atproto.server.refreshSession"
      public struct Input: Sendable, Hashable {
        public struct Headers: Sendable, Hashable {
          public var accept: [OpenAPIRuntime.AcceptHeaderContentType<ServerRefreshSession.AcceptableContentType>]
          public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<ServerRefreshSession.AcceptableContentType>] = .defaultValues()) {
            self.accept = accept
          }
        }
        public var headers: ServerRefreshSession.Input.Headers

        @frozen public enum Body: Sendable, Hashable {
          case json(Bool?)
        }
        public var body: ServerRefreshSession.Input.Body

        public init(
          headers: ServerRefreshSession.Input.Headers,
          body: ServerRefreshSession.Input.Body
        ) {
          self.headers = headers
          self.body = body
        }
      }
      @frozen public enum Output: Sendable, Hashable {
        public struct Ok: Sendable, Hashable {
          @frozen public enum Body: Sendable, Hashable {
            case json(Swift.Bool)
            public var json: Swift.Bool {
              get throws {
                switch self {
                case .json(let body):
                  return body
                }
              }
            }
          }

          public var body: ServerRefreshSession.Output.Ok.Body

          public init(body: ServerRefreshSession.Output.Ok.Body) {
            self.body = body
          }
        }

        case ok(ServerRefreshSession.Output.Ok)

        public var ok: ServerRefreshSession.Output.Ok {
          get throws {
            switch self {
            case .ok(let response):
              return response
            default:
              try throwUnexpectedResponseStatus(
                expectedStatus: "ok",
                response: self
              )
            }
          }
        }
        case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
        case json
        case other(Swift.String)
        public init?(rawValue: Swift.String) {
          switch rawValue.lowercased() {
          case "application/json":
            self = .json
          default:
            self = .other(rawValue)
          }
        }
        public var rawValue: Swift.String {
          switch self {
          case .other(let string):
            return string
          case .json:
            return "application/json"
          }
        }
        public static var allCases: [Self] {
          [
            .json
          ]
        }
      }
      public indirect enum Error: XRPCError {
          case accounttakedown(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "AccountTakedown":
                  self = .accounttakedown(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .accounttakedown:
                  return "AccountTakedown"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .accounttakedown(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct ServerRefreshSession_Output: Codable, Hashable, Sendable {
        public var accessJwt: String
        public var active: Bool?
        public var did: String
        public var didDoc: UnknownATPValue?
        public var handle: String
        public var refreshJwt: String
        public var status: ServerRefreshSession_Output_Status?
        public let _unknownValues: [String: AnyCodable]

        public init(accessJwt: String, active: Bool? = nil, did: String, didDoc: UnknownATPValue? = nil, handle: String, refreshJwt: String, status: ServerRefreshSession_Output_Status? = nil) {
            self.accessJwt = accessJwt
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.handle = handle
            self.refreshJwt = refreshJwt
            self.status = status
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case accessJwt
            case active
            case did
            case didDoc
            case handle
            case refreshJwt
            case status
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.accessJwt = try keyedContainer.decode(String.self, forKey: .accessJwt)
            self.active = try keyedContainer.decodeIfPresent(Bool.self, forKey: .active)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.didDoc = try keyedContainer.decodeIfPresent(UnknownATPValue.self, forKey: .didDoc)
            self.handle = try keyedContainer.decode(String.self, forKey: .handle)
            self.refreshJwt = try keyedContainer.decode(String.self, forKey: .refreshJwt)
            self.status = try keyedContainer.decodeIfPresent(ServerRefreshSession_Output_Status.self, forKey: .status)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.accessJwt, forKey: .accessJwt)
            try container.encodeIfPresent(self.active, forKey: .active)
            try container.encode(self.did, forKey: .did)
            try container.encodeIfPresent(self.didDoc, forKey: .didDoc)
            try container.encode(self.handle, forKey: .handle)
            try container.encode(self.refreshJwt, forKey: .refreshJwt)
            try container.encodeIfPresent(self.status, forKey: .status)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum ServerRefreshSession_Output_Status: RawRepresentable, Codable, Hashable, Sendable {
        case takendown
        case suspended
        case deactivated
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `ServerRefreshSession.Error` instead.")
    public typealias ServerRefreshSession_Error = ServerRefreshSession.Error
}
