//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum NotificationListNotifications {
      public static let id = "app.bsky.notification.listNotifications"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var cursor: String?
              public var limit: Int?
              public var priority: Bool?
              public var reasons: [String]?
              public var seenAt: String?

              public init(cursor: String? = nil, limit: Int? = nil, priority: Bool? = nil, reasons: [String]? = nil, seenAt: String? = nil) {
                self.cursor = cursor
                self.limit = limit
                self.priority = priority
                self.reasons = reasons
                self.seenAt = seenAt
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(appbskytypes.NotificationListNotifications_Output)
                        public var json: appbskytypes.NotificationListNotifications_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct NotificationListNotifications_Notification: Codable, Hashable, Sendable {
        public var author: ActorDefs_ProfileView
        public var cid: String
        public var indexedAt: String
        public var isRead: Bool
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var reason: NotificationListNotifications_Notification_Reason
        public var reasonSubject: String?
        public var record: UnknownATPValue
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(author: ActorDefs_ProfileView, cid: String, indexedAt: String, isRead: Bool, labels: [comatprototypes.LabelDefs_Label]? = nil, reason: NotificationListNotifications_Notification_Reason, reasonSubject: String? = nil, record: UnknownATPValue, uri: String) {
            self.author = author
            self.cid = cid
            self.indexedAt = indexedAt
            self.isRead = isRead
            self.labels = labels
            self.reason = reason
            self.reasonSubject = reasonSubject
            self.record = record
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case author
            case cid
            case indexedAt
            case isRead
            case labels
            case reason
            case reasonSubject
            case record
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.author = try keyedContainer.decode(ActorDefs_ProfileView.self, forKey: .author)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.indexedAt = try keyedContainer.decode(String.self, forKey: .indexedAt)
            self.isRead = try keyedContainer.decode(Bool.self, forKey: .isRead)
            self.labels = try keyedContainer.decodeIfPresent([comatprototypes.LabelDefs_Label].self, forKey: .labels)
            self.reason = try keyedContainer.decode(NotificationListNotifications_Notification_Reason.self, forKey: .reason)
            self.reasonSubject = try keyedContainer.decodeIfPresent(String.self, forKey: .reasonSubject)
            self.record = try keyedContainer.decode(UnknownATPValue.self, forKey: .record)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.author, forKey: .author)
            try container.encode(self.cid, forKey: .cid)
            try container.encode(self.indexedAt, forKey: .indexedAt)
            try container.encode(self.isRead, forKey: .isRead)
            try container.encodeIfPresent(self.labels, forKey: .labels)
            try container.encode(self.reason, forKey: .reason)
            try container.encodeIfPresent(self.reasonSubject, forKey: .reasonSubject)
            try container.encode(self.record, forKey: .record)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationListNotifications_Notification_Reason: RawRepresentable, Codable, Hashable, Sendable {
        case like
        case repost
        case follow
        case mention
        case reply
        case quote
        case starterpackJoined
        case verified
        case unverified
        case likeViaRepost
        case repostViaRepost
        case subscribedPost
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "like":
                self = .like
            case "repost":
                self = .repost
            case "follow":
                self = .follow
            case "mention":
                self = .mention
            case "reply":
                self = .reply
            case "quote":
                self = .quote
            case "starterpack-joined":
                self = .starterpackJoined
            case "verified":
                self = .verified
            case "unverified":
                self = .unverified
            case "like-via-repost":
                self = .likeViaRepost
            case "repost-via-repost":
                self = .repostViaRepost
            case "subscribed-post":
                self = .subscribedPost
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .like:
                "like"
            case .repost:
                "repost"
            case .follow:
                "follow"
            case .mention:
                "mention"
            case .reply:
                "reply"
            case .quote:
                "quote"
            case .starterpackJoined:
                "starterpack-joined"
            case .verified:
                "verified"
            case .unverified:
                "unverified"
            case .likeViaRepost:
                "like-via-repost"
            case .repostViaRepost:
                "repost-via-repost"
            case .subscribedPost:
                "subscribed-post"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public struct NotificationListNotifications_Output: Codable, Hashable, Sendable {
        public var cursor: String?
        public var notifications: [NotificationListNotifications_Notification]
        public var priority: Bool?
        public var seenAt: String?
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, notifications: [NotificationListNotifications_Notification], priority: Bool? = nil, seenAt: String? = nil) {
            self.cursor = cursor
            self.notifications = notifications
            self.priority = priority
            self.seenAt = seenAt
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case notifications
            case priority
            case seenAt
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.notifications = try keyedContainer.decode([NotificationListNotifications_Notification].self, forKey: .notifications)
            self.priority = try keyedContainer.decodeIfPresent(Bool.self, forKey: .priority)
            self.seenAt = try keyedContainer.decodeIfPresent(String.self, forKey: .seenAt)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.notifications, forKey: .notifications)
            try container.encodeIfPresent(self.priority, forKey: .priority)
            try container.encodeIfPresent(self.seenAt, forKey: .seenAt)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `NotificationListNotifications.Error` instead.")
    public typealias NotificationListNotifications_Error = NotificationListNotifications.Error
}
