//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public indirect enum ActorStatus_Embed: Codable, Hashable, Sendable {
        case embedExternal(EmbedExternal)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.embed.external":
                self = try .embedExternal(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .embedExternal(value):
                try container.encode("app.bsky.embed.external", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public indirect enum ActorStatus_Status: RawRepresentable, Codable, Hashable, Sendable {
        case appBskyActorStatusLive
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "app.bsky.actor.status#live":
                self = .appBskyActorStatusLive
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .appBskyActorStatusLive:
                "app.bsky.actor.status#live"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }
}

public struct appbskytypes_ActorStatus: ATProtoRecord {
    public static let nsId = "app.bsky.actor.status"
    public var type: String {
        Self.nsId
    }
    public let createdAt: String
    public let durationMinutes: Int?
    public let embed: appbskytypes.ActorStatus_Embed?
    public let status: appbskytypes.ActorStatus_Status
    public let _unknownValues: [String: AnyCodable]

    public init(createdAt: String, durationMinutes: Int? = nil, embed: appbskytypes.ActorStatus_Embed? = nil, status: appbskytypes.ActorStatus_Status) {
        self.createdAt = createdAt
        self.durationMinutes = durationMinutes
        self.embed = embed
        self.status = status
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case durationMinutes
        case embed
        case status
    }

    public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
        self.durationMinutes = try keyedContainer.decodeIfPresent(Int.self, forKey: .durationMinutes)
        self.embed = try keyedContainer.decodeIfPresent(appbskytypes.ActorStatus_Embed.self, forKey: .embed)
        self.status = try keyedContainer.decode(appbskytypes.ActorStatus_Status.self, forKey: .status)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.durationMinutes, forKey: .durationMinutes)
        try container.encodeIfPresent(self.embed, forKey: .embed)
        try container.encode(self.status, forKey: .status)
        try _unknownValues.encode(to: encoder)
    }
}
