//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum FeedDescribeFeedGenerator {
      public static let id = "app.bsky.feed.describeFeedGenerator"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {

              public init() {
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(appbskytypes.FeedDescribeFeedGenerator_Output)
                        public var json: appbskytypes.FeedDescribeFeedGenerator_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct FeedDescribeFeedGenerator_Feed: Codable, Hashable, Sendable {
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(uri: String) {
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct FeedDescribeFeedGenerator_Links: Codable, Hashable, Sendable {
        public var privacyPolicy: String?
        public var termsOfService: String?
        public let _unknownValues: [String: AnyCodable]

        public init(privacyPolicy: String? = nil, termsOfService: String? = nil) {
            self.privacyPolicy = privacyPolicy
            self.termsOfService = termsOfService
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case privacyPolicy
            case termsOfService
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.privacyPolicy = try keyedContainer.decodeIfPresent(String.self, forKey: .privacyPolicy)
            self.termsOfService = try keyedContainer.decodeIfPresent(String.self, forKey: .termsOfService)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.privacyPolicy, forKey: .privacyPolicy)
            try container.encodeIfPresent(self.termsOfService, forKey: .termsOfService)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct FeedDescribeFeedGenerator_Output: Codable, Hashable, Sendable {
        public var did: String
        public var feeds: [FeedDescribeFeedGenerator_Feed]
        public var links: FeedDescribeFeedGenerator_Links?
        public let _unknownValues: [String: AnyCodable]

        public init(did: String, feeds: [FeedDescribeFeedGenerator_Feed], links: FeedDescribeFeedGenerator_Links? = nil) {
            self.did = did
            self.feeds = feeds
            self.links = links
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
            case feeds
            case links
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            self.feeds = try keyedContainer.decode([FeedDescribeFeedGenerator_Feed].self, forKey: .feeds)
            self.links = try keyedContainer.decodeIfPresent(FeedDescribeFeedGenerator_Links.self, forKey: .links)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.did, forKey: .did)
            try container.encode(self.feeds, forKey: .feeds)
            try container.encodeIfPresent(self.links, forKey: .links)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `FeedDescribeFeedGenerator.Error` instead.")
    public typealias FeedDescribeFeedGenerator_Error = FeedDescribeFeedGenerator.Error
}
