//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum GraphUnmuteActor {
      public static let id = "app.bsky.graph.unmuteActor"
      public struct Input: Sendable, Hashable {
        public struct Headers: Sendable, Hashable {
          public var accept: [OpenAPIRuntime.AcceptHeaderContentType<GraphUnmuteActor.AcceptableContentType>]
          public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<GraphUnmuteActor.AcceptableContentType>] = .defaultValues()) {
            self.accept = accept
          }
        }
        public var headers: GraphUnmuteActor.Input.Headers

        @frozen public enum Body: Sendable, Hashable {
          case json(GraphUnmuteActor_Input)
        }
        public var body: GraphUnmuteActor.Input.Body

        public init(
          headers: GraphUnmuteActor.Input.Headers,
          body: GraphUnmuteActor.Input.Body
        ) {
          self.headers = headers
          self.body = body
        }
      }
      @frozen public enum Output: Sendable, Hashable {
        public struct Ok: Sendable, Hashable {
          @frozen public enum Body: Sendable, Hashable {
            case json(Swift.Bool)
            public var json: Swift.Bool {
              get throws {
                switch self {
                case .json(let body):
                  return body
                }
              }
            }
          }

          public var body: GraphUnmuteActor.Output.Ok.Body

          public init(body: GraphUnmuteActor.Output.Ok.Body) {
            self.body = body
          }
        }

        case ok(GraphUnmuteActor.Output.Ok)

        public var ok: GraphUnmuteActor.Output.Ok {
          get throws {
            switch self {
            case .ok(let response):
              return response
            default:
              try throwUnexpectedResponseStatus(
                expectedStatus: "ok",
                response: self
              )
            }
          }
        }
        case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
        case json
        case other(Swift.String)
        public init?(rawValue: Swift.String) {
          switch rawValue.lowercased() {
          case "application/json":
            self = .json
          default:
            self = .other(rawValue)
          }
        }
        public var rawValue: Swift.String {
          switch self {
          case .other(let string):
            return string
          case .json:
            return "application/json"
          }
        }
        public static var allCases: [Self] {
          [
            .json
          ]
        }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct GraphUnmuteActor_Input: Codable, Hashable, Sendable {
        public var actor: String
        public let _unknownValues: [String: AnyCodable]

        public init(actor: String) {
            self.actor = actor
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actor
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actor = try keyedContainer.decode(String.self, forKey: .actor)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.actor, forKey: .actor)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `GraphUnmuteActor.Error` instead.")
    public typealias GraphUnmuteActor_Error = GraphUnmuteActor.Error
}
