//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public indirect enum GraphList_Labels: Codable, Hashable, Sendable {
        case comAtprotoLabelDefsSelfLabels(comatprototypes.LabelDefs_SelfLabels)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.label.defs#selfLabels":
                self = try .comAtprotoLabelDefsSelfLabels(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .comAtprotoLabelDefsSelfLabels(value):
                try container.encode("com.atproto.label.defs#selfLabels", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }
}

public struct appbskytypes_GraphList: ATProtoRecord {
    public static let nsId = "app.bsky.graph.list"
    public var type: String {
        Self.nsId
    }
    public let avatar: LexBlob?
    public let createdAt: String
    public let description: String?
    public let descriptionFacets: [appbskytypes.RichtextFacet]?
    public let labels: appbskytypes.GraphList_Labels?
    public let name: String
    public let purpose: appbskytypes.GraphDefs_ListPurpose
    public let _unknownValues: [String: AnyCodable]

    public init(avatar: LexBlob? = nil, createdAt: String, description: String? = nil, descriptionFacets: [appbskytypes.RichtextFacet]? = nil, labels: appbskytypes.GraphList_Labels? = nil, name: String, purpose: appbskytypes.GraphDefs_ListPurpose) {
        self.avatar = avatar
        self.createdAt = createdAt
        self.description = description
        self.descriptionFacets = descriptionFacets
        self.labels = labels
        self.name = name
        self.purpose = purpose
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case avatar
        case createdAt
        case description
        case descriptionFacets
        case labels
        case name
        case purpose
    }

    public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.avatar = try keyedContainer.decodeIfPresent(LexBlob.self, forKey: .avatar)
        self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
        self.description = try keyedContainer.decodeIfPresent(String.self, forKey: .description)
        self.descriptionFacets = try keyedContainer.decodeIfPresent([appbskytypes.RichtextFacet].self, forKey: .descriptionFacets)
        self.labels = try keyedContainer.decodeIfPresent(appbskytypes.GraphList_Labels.self, forKey: .labels)
        self.name = try keyedContainer.decode(String.self, forKey: .name)
        self.purpose = try keyedContainer.decode(appbskytypes.GraphDefs_ListPurpose.self, forKey: .purpose)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.avatar, forKey: .avatar)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.descriptionFacets, forKey: .descriptionFacets)
        try container.encodeIfPresent(self.labels, forKey: .labels)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.purpose, forKey: .purpose)
        try _unknownValues.encode(to: encoder)
    }
}
