//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public struct RichtextFacet: Codable, Hashable, Sendable {
        public var features: [RichtextFacet_Features_Elem]
        public var index: RichtextFacet_ByteSlice
        public let _unknownValues: [String: AnyCodable]

        public init(features: [RichtextFacet_Features_Elem], index: RichtextFacet_ByteSlice) {
            self.features = features
            self.index = index
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case features
            case index
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.features = try keyedContainer.decode([RichtextFacet_Features_Elem].self, forKey: .features)
            self.index = try keyedContainer.decode(RichtextFacet_ByteSlice.self, forKey: .index)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.features, forKey: .features)
            try container.encode(self.index, forKey: .index)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RichtextFacet_ByteSlice: Codable, Hashable, Sendable {
        public var byteEnd: Int
        public var byteStart: Int
        public let _unknownValues: [String: AnyCodable]

        public init(byteEnd: Int, byteStart: Int) {
            self.byteEnd = byteEnd
            self.byteStart = byteStart
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case byteEnd
            case byteStart
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.byteEnd = try keyedContainer.decode(Int.self, forKey: .byteEnd)
            self.byteStart = try keyedContainer.decode(Int.self, forKey: .byteStart)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.byteEnd, forKey: .byteEnd)
            try container.encode(self.byteStart, forKey: .byteStart)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum RichtextFacet_Features_Elem: Codable, Hashable, Sendable {
        case richtextFacetMention(RichtextFacet_Mention)
        case richtextFacetLink(RichtextFacet_Link)
        case richtextFacetTag(RichtextFacet_Tag)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.richtext.facet#mention":
                self = try .richtextFacetMention(.init(from: decoder))
            case "app.bsky.richtext.facet#link":
                self = try .richtextFacetLink(.init(from: decoder))
            case "app.bsky.richtext.facet#tag":
                self = try .richtextFacetTag(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .richtextFacetMention(value):
                try container.encode("app.bsky.richtext.facet#mention", forKey: .type)
                try value.encode(to: encoder)
            case let .richtextFacetLink(value):
                try container.encode("app.bsky.richtext.facet#link", forKey: .type)
                try value.encode(to: encoder)
            case let .richtextFacetTag(value):
                try container.encode("app.bsky.richtext.facet#tag", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public struct RichtextFacet_Link: Codable, Hashable, Sendable {
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(uri: String) {
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RichtextFacet_Mention: Codable, Hashable, Sendable {
        public var did: String
        public let _unknownValues: [String: AnyCodable]

        public init(did: String) {
            self.did = did
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case did
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.did = try keyedContainer.decode(String.self, forKey: .did)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.did, forKey: .did)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct RichtextFacet_Tag: Codable, Hashable, Sendable {
        public var tag: String
        public let _unknownValues: [String: AnyCodable]

        public init(tag: String) {
            self.tag = tag
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case tag
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.tag = try keyedContainer.decode(String.self, forKey: .tag)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.tag, forKey: .tag)
            try _unknownValues.encode(to: encoder)
        }
    }
}
