//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum UnspeccedGetTaggedSuggestions {
      public static let id = "app.bsky.unspecced.getTaggedSuggestions"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {

              public init() {
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(appbskytypes.UnspeccedGetTaggedSuggestions_Output)
                        public var json: appbskytypes.UnspeccedGetTaggedSuggestions_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct UnspeccedGetTaggedSuggestions_Output: Codable, Hashable, Sendable {
        public var suggestions: [UnspeccedGetTaggedSuggestions_Suggestion]
        public let _unknownValues: [String: AnyCodable]

        public init(suggestions: [UnspeccedGetTaggedSuggestions_Suggestion]) {
            self.suggestions = suggestions
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case suggestions
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.suggestions = try keyedContainer.decode([UnspeccedGetTaggedSuggestions_Suggestion].self, forKey: .suggestions)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.suggestions, forKey: .suggestions)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct UnspeccedGetTaggedSuggestions_Suggestion: Codable, Hashable, Sendable {
        public var subject: String
        public var subjectType: UnspeccedGetTaggedSuggestions_Suggestion_SubjectType
        public var tag: String
        public let _unknownValues: [String: AnyCodable]

        public init(subject: String, subjectType: UnspeccedGetTaggedSuggestions_Suggestion_SubjectType, tag: String) {
            self.subject = subject
            self.subjectType = subjectType
            self.tag = tag
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case subject
            case subjectType
            case tag
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.subject = try keyedContainer.decode(String.self, forKey: .subject)
            self.subjectType = try keyedContainer.decode(UnspeccedGetTaggedSuggestions_Suggestion_SubjectType.self, forKey: .subjectType)
            self.tag = try keyedContainer.decode(String.self, forKey: .tag)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.subject, forKey: .subject)
            try container.encode(self.subjectType, forKey: .subjectType)
            try container.encode(self.tag, forKey: .tag)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum UnspeccedGetTaggedSuggestions_Suggestion_SubjectType: RawRepresentable, Codable, Hashable, Sendable {
        case actor
        case feed
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "actor":
                self = .actor
            case "feed":
                self = .feed
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .actor:
                "actor"
            case .feed:
                "feed"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `UnspeccedGetTaggedSuggestions.Error` instead.")
    public typealias UnspeccedGetTaggedSuggestions_Error = UnspeccedGetTaggedSuggestions.Error
}
