//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum NotificationUnregisterPush {
      public static let id = "app.bsky.notification.unregisterPush"
      public struct Input: Sendable, Hashable {
        public struct Headers: Sendable, Hashable {
          public var accept: [OpenAPIRuntime.AcceptHeaderContentType<NotificationUnregisterPush.AcceptableContentType>]
          public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<NotificationUnregisterPush.AcceptableContentType>] = .defaultValues()) {
            self.accept = accept
          }
        }
        public var headers: NotificationUnregisterPush.Input.Headers

        @frozen public enum Body: Sendable, Hashable {
          case json(NotificationUnregisterPush_Input)
        }
        public var body: NotificationUnregisterPush.Input.Body

        public init(
          headers: NotificationUnregisterPush.Input.Headers,
          body: NotificationUnregisterPush.Input.Body
        ) {
          self.headers = headers
          self.body = body
        }
      }
      @frozen public enum Output: Sendable, Hashable {
        public struct Ok: Sendable, Hashable {
          @frozen public enum Body: Sendable, Hashable {
            case json(Swift.Bool)
            public var json: Swift.Bool {
              get throws {
                switch self {
                case .json(let body):
                  return body
                }
              }
            }
          }

          public var body: NotificationUnregisterPush.Output.Ok.Body

          public init(body: NotificationUnregisterPush.Output.Ok.Body) {
            self.body = body
          }
        }

        case ok(NotificationUnregisterPush.Output.Ok)

        public var ok: NotificationUnregisterPush.Output.Ok {
          get throws {
            switch self {
            case .ok(let response):
              return response
            default:
              try throwUnexpectedResponseStatus(
                expectedStatus: "ok",
                response: self
              )
            }
          }
        }
        case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
        case json
        case other(Swift.String)
        public init?(rawValue: Swift.String) {
          switch rawValue.lowercased() {
          case "application/json":
            self = .json
          default:
            self = .other(rawValue)
          }
        }
        public var rawValue: Swift.String {
          switch self {
          case .other(let string):
            return string
          case .json:
            return "application/json"
          }
        }
        public static var allCases: [Self] {
          [
            .json
          ]
        }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct NotificationUnregisterPush_Input: Codable, Hashable, Sendable {
        public var appId: String
        public var platform: NotificationUnregisterPush_Input_Platform
        public var serviceDid: String
        public var token: String
        public let _unknownValues: [String: AnyCodable]

        public init(appId: String, platform: NotificationUnregisterPush_Input_Platform, serviceDid: String, token: String) {
            self.appId = appId
            self.platform = platform
            self.serviceDid = serviceDid
            self.token = token
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case appId
            case platform
            case serviceDid
            case token
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.appId = try keyedContainer.decode(String.self, forKey: .appId)
            self.platform = try keyedContainer.decode(NotificationUnregisterPush_Input_Platform.self, forKey: .platform)
            self.serviceDid = try keyedContainer.decode(String.self, forKey: .serviceDid)
            self.token = try keyedContainer.decode(String.self, forKey: .token)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.appId, forKey: .appId)
            try container.encode(self.platform, forKey: .platform)
            try container.encode(self.serviceDid, forKey: .serviceDid)
            try container.encode(self.token, forKey: .token)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum NotificationUnregisterPush_Input_Platform: RawRepresentable, Codable, Hashable, Sendable {
        case ios
        case android
        case web
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "ios":
                self = .ios
            case "android":
                self = .android
            case "web":
                self = .web
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .ios:
                "ios"
            case .android:
                "android"
            case .web:
                "web"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `NotificationUnregisterPush.Error` instead.")
    public typealias NotificationUnregisterPush_Error = NotificationUnregisterPush.Error
}
