//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public struct EmbedRecord: Codable, Hashable, Sendable {
        public var record: comatprototypes.RepoStrongRef
        public let _unknownValues: [String: AnyCodable]

        public init(record: comatprototypes.RepoStrongRef) {
            self.record = record
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case record
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.record = try keyedContainer.decode(comatprototypes.RepoStrongRef.self, forKey: .record)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.record, forKey: .record)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedRecord_View: Codable, Hashable, Sendable {
        public var record: EmbedRecord_View_Record
        public let _unknownValues: [String: AnyCodable]

        public init(record: EmbedRecord_View_Record) {
            self.record = record
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case record
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.record = try keyedContainer.decode(EmbedRecord_View_Record.self, forKey: .record)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.record, forKey: .record)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum EmbedRecord_View_Record: Codable, Hashable, Sendable {
        case embedRecordViewRecord(EmbedRecord_ViewRecord)
        case embedRecordViewNotFound(EmbedRecord_ViewNotFound)
        case embedRecordViewBlocked(EmbedRecord_ViewBlocked)
        case embedRecordViewDetached(EmbedRecord_ViewDetached)
        case feedDefsGeneratorView(FeedDefs_GeneratorView)
        case graphDefsListView(GraphDefs_ListView)
        case labelerDefsLabelerView(LabelerDefs_LabelerView)
        case graphDefsStarterPackViewBasic(GraphDefs_StarterPackViewBasic)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.embed.record#viewRecord":
                self = try .embedRecordViewRecord(.init(from: decoder))
            case "app.bsky.embed.record#viewNotFound":
                self = try .embedRecordViewNotFound(.init(from: decoder))
            case "app.bsky.embed.record#viewBlocked":
                self = try .embedRecordViewBlocked(.init(from: decoder))
            case "app.bsky.embed.record#viewDetached":
                self = try .embedRecordViewDetached(.init(from: decoder))
            case "app.bsky.feed.defs#generatorView":
                self = try .feedDefsGeneratorView(.init(from: decoder))
            case "app.bsky.graph.defs#listView":
                self = try .graphDefsListView(.init(from: decoder))
            case "app.bsky.labeler.defs#labelerView":
                self = try .labelerDefsLabelerView(.init(from: decoder))
            case "app.bsky.graph.defs#starterPackViewBasic":
                self = try .graphDefsStarterPackViewBasic(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .embedRecordViewRecord(value):
                try container.encode("app.bsky.embed.record#viewRecord", forKey: .type)
                try value.encode(to: encoder)
            case let .embedRecordViewNotFound(value):
                try container.encode("app.bsky.embed.record#viewNotFound", forKey: .type)
                try value.encode(to: encoder)
            case let .embedRecordViewBlocked(value):
                try container.encode("app.bsky.embed.record#viewBlocked", forKey: .type)
                try value.encode(to: encoder)
            case let .embedRecordViewDetached(value):
                try container.encode("app.bsky.embed.record#viewDetached", forKey: .type)
                try value.encode(to: encoder)
            case let .feedDefsGeneratorView(value):
                try container.encode("app.bsky.feed.defs#generatorView", forKey: .type)
                try value.encode(to: encoder)
            case let .graphDefsListView(value):
                try container.encode("app.bsky.graph.defs#listView", forKey: .type)
                try value.encode(to: encoder)
            case let .labelerDefsLabelerView(value):
                try container.encode("app.bsky.labeler.defs#labelerView", forKey: .type)
                try value.encode(to: encoder)
            case let .graphDefsStarterPackViewBasic(value):
                try container.encode("app.bsky.graph.defs#starterPackViewBasic", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }

    public struct EmbedRecord_ViewBlocked: Codable, Hashable, Sendable {
        public var author: FeedDefs_BlockedAuthor
        public var blocked: Bool
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(author: FeedDefs_BlockedAuthor, blocked: Bool, uri: String) {
            self.author = author
            self.blocked = blocked
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case author
            case blocked
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.author = try keyedContainer.decode(FeedDefs_BlockedAuthor.self, forKey: .author)
            self.blocked = try keyedContainer.decode(Bool.self, forKey: .blocked)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.author, forKey: .author)
            try container.encode(self.blocked, forKey: .blocked)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedRecord_ViewDetached: Codable, Hashable, Sendable {
        public var detached: Bool
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(detached: Bool, uri: String) {
            self.detached = detached
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case detached
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.detached = try keyedContainer.decode(Bool.self, forKey: .detached)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.detached, forKey: .detached)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedRecord_ViewNotFound: Codable, Hashable, Sendable {
        public var notFound: Bool
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(notFound: Bool, uri: String) {
            self.notFound = notFound
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case notFound
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.notFound = try keyedContainer.decode(Bool.self, forKey: .notFound)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.notFound, forKey: .notFound)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedRecord_ViewRecord: Codable, Hashable, Sendable {
        public var author: ActorDefs_ProfileViewBasic
        public var cid: String
        public var embeds: [EmbedRecord_ViewRecord_Embeds_Elem]?
        public var indexedAt: String
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var likeCount: Int?
        public var quoteCount: Int?
        public var replyCount: Int?
        public var repostCount: Int?
        public var uri: String
        public var value: UnknownATPValue
        public let _unknownValues: [String: AnyCodable]

        public init(author: ActorDefs_ProfileViewBasic, cid: String, embeds: [EmbedRecord_ViewRecord_Embeds_Elem]? = nil, indexedAt: String, labels: [comatprototypes.LabelDefs_Label]? = nil, likeCount: Int? = nil, quoteCount: Int? = nil, replyCount: Int? = nil, repostCount: Int? = nil, uri: String, value: UnknownATPValue) {
            self.author = author
            self.cid = cid
            self.embeds = embeds
            self.indexedAt = indexedAt
            self.labels = labels
            self.likeCount = likeCount
            self.quoteCount = quoteCount
            self.replyCount = replyCount
            self.repostCount = repostCount
            self.uri = uri
            self.value = value
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case author
            case cid
            case embeds
            case indexedAt
            case labels
            case likeCount
            case quoteCount
            case replyCount
            case repostCount
            case uri
            case value
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.author = try keyedContainer.decode(ActorDefs_ProfileViewBasic.self, forKey: .author)
            self.cid = try keyedContainer.decode(String.self, forKey: .cid)
            self.embeds = try keyedContainer.decodeIfPresent([EmbedRecord_ViewRecord_Embeds_Elem].self, forKey: .embeds)
            self.indexedAt = try keyedContainer.decode(String.self, forKey: .indexedAt)
            self.labels = try keyedContainer.decodeIfPresent([comatprototypes.LabelDefs_Label].self, forKey: .labels)
            self.likeCount = try keyedContainer.decodeIfPresent(Int.self, forKey: .likeCount)
            self.quoteCount = try keyedContainer.decodeIfPresent(Int.self, forKey: .quoteCount)
            self.replyCount = try keyedContainer.decodeIfPresent(Int.self, forKey: .replyCount)
            self.repostCount = try keyedContainer.decodeIfPresent(Int.self, forKey: .repostCount)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            self.value = try keyedContainer.decode(UnknownATPValue.self, forKey: .value)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.author, forKey: .author)
            try container.encode(self.cid, forKey: .cid)
            try container.encodeIfPresent(self.embeds, forKey: .embeds)
            try container.encode(self.indexedAt, forKey: .indexedAt)
            try container.encodeIfPresent(self.labels, forKey: .labels)
            try container.encodeIfPresent(self.likeCount, forKey: .likeCount)
            try container.encodeIfPresent(self.quoteCount, forKey: .quoteCount)
            try container.encodeIfPresent(self.replyCount, forKey: .replyCount)
            try container.encodeIfPresent(self.repostCount, forKey: .repostCount)
            try container.encode(self.uri, forKey: .uri)
            try container.encode(self.value, forKey: .value)
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum EmbedRecord_ViewRecord_Embeds_Elem: Codable, Hashable, Sendable {
        case embedImagesView(EmbedImages_View)
        case embedVideoView(EmbedVideo_View)
        case embedExternalView(EmbedExternal_View)
        case embedRecordView(EmbedRecord_View)
        case embedRecordWithMediaView(EmbedRecordWithMedia_View)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.embed.images#view":
                self = try .embedImagesView(.init(from: decoder))
            case "app.bsky.embed.video#view":
                self = try .embedVideoView(.init(from: decoder))
            case "app.bsky.embed.external#view":
                self = try .embedExternalView(.init(from: decoder))
            case "app.bsky.embed.record#view":
                self = try .embedRecordView(.init(from: decoder))
            case "app.bsky.embed.recordWithMedia#view":
                self = try .embedRecordWithMediaView(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .embedImagesView(value):
                try container.encode("app.bsky.embed.images#view", forKey: .type)
                try value.encode(to: encoder)
            case let .embedVideoView(value):
                try container.encode("app.bsky.embed.video#view", forKey: .type)
                try value.encode(to: encoder)
            case let .embedExternalView(value):
                try container.encode("app.bsky.embed.external#view", forKey: .type)
                try value.encode(to: encoder)
            case let .embedRecordView(value):
                try container.encode("app.bsky.embed.record#view", forKey: .type)
                try value.encode(to: encoder)
            case let .embedRecordWithMediaView(value):
                try container.encode("app.bsky.embed.recordWithMedia#view", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }
}
