//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public struct EmbedDefs_AspectRatio: Codable, Hashable, Sendable {
        public var height: Int
        public var width: Int
        public let _unknownValues: [String: AnyCodable]

        public init(height: Int, width: Int) {
            self.height = height
            self.width = width
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case height
            case width
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.height = try keyedContainer.decode(Int.self, forKey: .height)
            self.width = try keyedContainer.decode(Int.self, forKey: .width)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.height, forKey: .height)
            try container.encode(self.width, forKey: .width)
            try _unknownValues.encode(to: encoder)
        }
    }
}
