//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum UnspeccedSearchStarterPacksSkeleton {
      public static let id = "app.bsky.unspecced.searchStarterPacksSkeleton"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var cursor: String?
              public var limit: Int?
              public var q: String
              public var viewer: String?

              public init(cursor: String? = nil, limit: Int? = nil, q: String, viewer: String? = nil) {
                self.cursor = cursor
                self.limit = limit
                self.q = q
                self.viewer = viewer
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(appbskytypes.UnspeccedSearchStarterPacksSkeleton_Output)
                        public var json: appbskytypes.UnspeccedSearchStarterPacksSkeleton_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case badquerystring(String?)
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              case "BadQueryString":
                  self = .badquerystring(error.message)
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case .badquerystring:
                  return "BadQueryString"
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .badquerystring(message):
                  return message
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct UnspeccedSearchStarterPacksSkeleton_Output: Codable, Hashable, Sendable {
        public var cursor: String?
        public var hitsTotal: Int?
        public var starterPacks: [UnspeccedDefs_SkeletonSearchStarterPack]
        public let _unknownValues: [String: AnyCodable]

        public init(cursor: String? = nil, hitsTotal: Int? = nil, starterPacks: [UnspeccedDefs_SkeletonSearchStarterPack]) {
            self.cursor = cursor
            self.hitsTotal = hitsTotal
            self.starterPacks = starterPacks
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case hitsTotal
            case starterPacks
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.hitsTotal = try keyedContainer.decodeIfPresent(Int.self, forKey: .hitsTotal)
            self.starterPacks = try keyedContainer.decode([UnspeccedDefs_SkeletonSearchStarterPack].self, forKey: .starterPacks)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encodeIfPresent(self.hitsTotal, forKey: .hitsTotal)
            try container.encode(self.starterPacks, forKey: .starterPacks)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `UnspeccedSearchStarterPacksSkeleton.Error` instead.")
    public typealias UnspeccedSearchStarterPacksSkeleton_Error = UnspeccedSearchStarterPacksSkeleton.Error
}
