//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public indirect enum NotificationDeclaration_AllowSubscriptions: RawRepresentable, Codable, Hashable, Sendable {
        case followers
        case mutuals
        case none
        case _other(String)

        public init(rawValue: String) {
            switch rawValue {
            case "followers":
                self = .followers
            case "mutuals":
                self = .mutuals
            case "none":
                self = .none
            default:
                self = ._other(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .followers:
                "followers"
            case .mutuals:
                "mutuals"
            case .none:
                "none"
            case let ._other(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self(rawValue: rawValue)
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }
}

public struct appbskytypes_NotificationDeclaration: ATProtoRecord {
    public static let nsId = "app.bsky.notification.declaration"
    public var type: String {
        Self.nsId
    }
    public let allowSubscriptions: appbskytypes.NotificationDeclaration_AllowSubscriptions
    public let _unknownValues: [String: AnyCodable]

    public init(allowSubscriptions: appbskytypes.NotificationDeclaration_AllowSubscriptions) {
        self.allowSubscriptions = allowSubscriptions
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case allowSubscriptions
    }

    public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.allowSubscriptions = try keyedContainer.decode(appbskytypes.NotificationDeclaration_AllowSubscriptions.self, forKey: .allowSubscriptions)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.allowSubscriptions, forKey: .allowSubscriptions)
        try _unknownValues.encode(to: encoder)
    }
}
