//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public indirect enum LabelerService_Labels: Codable, Hashable, Sendable {
        case comAtprotoLabelDefsSelfLabels(comatprototypes.LabelDefs_SelfLabels)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "com.atproto.label.defs#selfLabels":
                self = try .comAtprotoLabelDefsSelfLabels(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .comAtprotoLabelDefsSelfLabels(value):
                try container.encode("com.atproto.label.defs#selfLabels", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }
}

public struct appbskytypes_LabelerService: ATProtoRecord {
    public static let nsId = "app.bsky.labeler.service"
    public var type: String {
        Self.nsId
    }
    public let createdAt: String
    public let labels: appbskytypes.LabelerService_Labels?
    public let policies: appbskytypes.LabelerDefs_LabelerPolicies
    public let reasonTypes: [comatprototypes.ModerationDefs_ReasonType]?
    public let subjectCollections: [String]?
    public let subjectTypes: [comatprototypes.ModerationDefs_SubjectType]?
    public let _unknownValues: [String: AnyCodable]

    public init(createdAt: String, labels: appbskytypes.LabelerService_Labels? = nil, policies: appbskytypes.LabelerDefs_LabelerPolicies, reasonTypes: [comatprototypes.ModerationDefs_ReasonType]? = nil, subjectCollections: [String]? = nil, subjectTypes: [comatprototypes.ModerationDefs_SubjectType]? = nil) {
        self.createdAt = createdAt
        self.labels = labels
        self.policies = policies
        self.reasonTypes = reasonTypes
        self.subjectCollections = subjectCollections
        self.subjectTypes = subjectTypes
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case labels
        case policies
        case reasonTypes
        case subjectCollections
        case subjectTypes
    }

    public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
        self.labels = try keyedContainer.decodeIfPresent(appbskytypes.LabelerService_Labels.self, forKey: .labels)
        self.policies = try keyedContainer.decode(appbskytypes.LabelerDefs_LabelerPolicies.self, forKey: .policies)
        self.reasonTypes = try keyedContainer.decodeIfPresent([comatprototypes.ModerationDefs_ReasonType].self, forKey: .reasonTypes)
        self.subjectCollections = try keyedContainer.decodeIfPresent([String].self, forKey: .subjectCollections)
        self.subjectTypes = try keyedContainer.decodeIfPresent([comatprototypes.ModerationDefs_SubjectType].self, forKey: .subjectTypes)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.labels, forKey: .labels)
        try container.encode(self.policies, forKey: .policies)
        try container.encodeIfPresent(self.reasonTypes, forKey: .reasonTypes)
        try container.encodeIfPresent(self.subjectCollections, forKey: .subjectCollections)
        try container.encodeIfPresent(self.subjectTypes, forKey: .subjectTypes)
        try _unknownValues.encode(to: encoder)
    }
}
