//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public enum FeedGetLikes {
      public static let id = "app.bsky.feed.getLikes"
      public struct Input: Sendable, Hashable {
          public struct Query: Sendable, Hashable {
              public var cid: String?
              public var cursor: String?
              public var limit: Int?
              public var uri: String

              public init(cid: String? = nil, cursor: String? = nil, limit: Int? = nil, uri: String) {
                self.cid = cid
                self.cursor = cursor
                self.limit = limit
                self.uri = uri
            }
        }
          public var query: Input.Query
          public struct Headers: Sendable, Hashable {
              public var accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>]
              public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<AcceptableContentType>] = .defaultValues()) {
                  self.accept = accept
              }
          }
          public var headers: Input.Headers
          public init(
            query: Input.Query,
                    headers: Input.Headers = .init()
          ) {
              self.query = query
              self.headers = headers
          }
      }
      @frozen public enum Output: Sendable, Hashable {
                public struct Ok: Sendable, Hashable {
                    @frozen public enum Body: Sendable, Hashable {
                        case json(appbskytypes.FeedGetLikes_Output)
                        public var json: appbskytypes.FeedGetLikes_Output {
                            get throws {
                                switch self {
                                case let .json(body):
                                    return body
                                }
                          }
                        }
                  }
                    public var body: Output.Ok.Body
                    public init(body: Output.Ok.Body) {
                        self.body = body
                  }
              }
                case ok(Output.Ok)
                public var ok: Output.Ok {
                    get throws {
                        switch self {
                        case let .ok(response):
                            return response
                        default:
                            try throwUnexpectedResponseStatus(
                                expectedStatus: "ok",
                                response: self
                            )
                        }
                    }
                }
                case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
      }
      @frozen public enum AcceptableContentType: AcceptableProtocol {
          case json
          case other(String)
          public init?(rawValue: String) {
                  switch rawValue.lowercased() {
                  case "application/json":
                      self = .json
                  default:
                              self = .other(rawValue)
                  }
          }
              public var rawValue: String {
                  switch self {
                  case let .other(string):
                      return string
                  case .json:
                      return "application/json"
                  }
              }
              public static var allCases: [Self] {
                  [
                      .json
                  ]
              }
      }
      public indirect enum Error: XRPCError {
          case unexpected(error: String?, message: String?)

          public init(error: UnExpectedError) {
              switch error.error {
              default:
                  self = .unexpected(error: error.error, message: error.message)
              }
          }

          public var error: String? {
              switch self {
              case let .unexpected(error, _):
                  return error
              }
          }

          public var message: String? {
              switch self {
              case let .unexpected(_, message):
                  return message
              }
          }
      }
    }

    public struct FeedGetLikes_Like: Codable, Hashable, Sendable {
        public var actor: ActorDefs_ProfileView
        public var createdAt: String
        public var indexedAt: String
        public let _unknownValues: [String: AnyCodable]

        public init(actor: ActorDefs_ProfileView, createdAt: String, indexedAt: String) {
            self.actor = actor
            self.createdAt = createdAt
            self.indexedAt = indexedAt
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case actor
            case createdAt
            case indexedAt
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.actor = try keyedContainer.decode(ActorDefs_ProfileView.self, forKey: .actor)
            self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
            self.indexedAt = try keyedContainer.decode(String.self, forKey: .indexedAt)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.actor, forKey: .actor)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.indexedAt, forKey: .indexedAt)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct FeedGetLikes_Output: Codable, Hashable, Sendable {
        public var cid: String?
        public var cursor: String?
        public var likes: [FeedGetLikes_Like]
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(cid: String? = nil, cursor: String? = nil, likes: [FeedGetLikes_Like], uri: String) {
            self.cid = cid
            self.cursor = cursor
            self.likes = likes
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case cursor
            case likes
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.cid = try keyedContainer.decodeIfPresent(String.self, forKey: .cid)
            self.cursor = try keyedContainer.decodeIfPresent(String.self, forKey: .cursor)
            self.likes = try keyedContainer.decode([FeedGetLikes_Like].self, forKey: .likes)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(self.cid, forKey: .cid)
            try container.encodeIfPresent(self.cursor, forKey: .cursor)
            try container.encode(self.likes, forKey: .likes)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    @available(*, deprecated, message: "Use `FeedGetLikes.Error` instead.")
    public typealias FeedGetLikes_Error = FeedGetLikes.Error
}
