//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public struct FeedPostgate_DisableRule: Codable, Hashable, Sendable {
        public let _unknownValues: [String: AnyCodable]

        public init() {
            self._unknownValues = [:]
        }

        public init(from decoder: any Decoder) throws {
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            try _unknownValues.encode(to: encoder)
        }
    }

    public indirect enum FeedPostgate_EmbeddingRules_Elem: Codable, Hashable, Sendable {
        case feedPostgateDisableRule(FeedPostgate_DisableRule)
        case _other(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.feed.postgate#disableRule":
                self = try .feedPostgateDisableRule(.init(from: decoder))
            default:
                self = try ._other(.init(from: decoder))
            }
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .feedPostgateDisableRule(value):
                try container.encode("app.bsky.feed.postgate#disableRule", forKey: .type)
                try value.encode(to: encoder)
            case let ._other(value):
                try value.encode(to: encoder)
            }
        }
    }
}

public struct appbskytypes_FeedPostgate: ATProtoRecord {
    public static let nsId = "app.bsky.feed.postgate"
    public var type: String {
        Self.nsId
    }
    public let createdAt: String
    public let detachedEmbeddingUris: [String]?
    public let embeddingRules: [appbskytypes.FeedPostgate_EmbeddingRules_Elem]?
    public let post: String
    public let _unknownValues: [String: AnyCodable]

    public init(createdAt: String, detachedEmbeddingUris: [String]? = nil, embeddingRules: [appbskytypes.FeedPostgate_EmbeddingRules_Elem]? = nil, post: String) {
        self.createdAt = createdAt
        self.detachedEmbeddingUris = detachedEmbeddingUris
        self.embeddingRules = embeddingRules
        self.post = post
        self._unknownValues = [:]
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case detachedEmbeddingUris
        case embeddingRules
        case post
    }

    public init(from decoder: any Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try keyedContainer.decode(String.self, forKey: .createdAt)
        self.detachedEmbeddingUris = try keyedContainer.decodeIfPresent([String].self, forKey: .detachedEmbeddingUris)
        self.embeddingRules = try keyedContainer.decodeIfPresent([appbskytypes.FeedPostgate_EmbeddingRules_Elem].self, forKey: .embeddingRules)
        self.post = try keyedContainer.decode(String.self, forKey: .post)
        let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
        var _unknownValues = [String: AnyCodable]()
        for key in unknownContainer.allKeys {
            guard CodingKeys(rawValue: key.stringValue) == nil else {
                continue
            }
            _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
        }
        self._unknownValues = _unknownValues
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.detachedEmbeddingUris, forKey: .detachedEmbeddingUris)
        try container.encodeIfPresent(self.embeddingRules, forKey: .embeddingRules)
        try container.encode(self.post, forKey: .post)
        try _unknownValues.encode(to: encoder)
    }
}
