//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation
@_spi(Generated) import OpenAPIRuntime

extension appbskytypes {
    public struct EmbedExternal: Codable, Hashable, Sendable {
        public var external: EmbedExternal_External
        public let _unknownValues: [String: AnyCodable]

        public init(external: EmbedExternal_External) {
            self.external = external
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case external
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.external = try keyedContainer.decode(EmbedExternal_External.self, forKey: .external)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.external, forKey: .external)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedExternal_External: Codable, Hashable, Sendable {
        public var description: String
        public var thumb: LexBlob?
        public var title: String
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(description: String, thumb: LexBlob? = nil, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.description = try keyedContainer.decode(String.self, forKey: .description)
            self.thumb = try keyedContainer.decodeIfPresent(LexBlob.self, forKey: .thumb)
            self.title = try keyedContainer.decode(String.self, forKey: .title)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.description, forKey: .description)
            try container.encodeIfPresent(self.thumb, forKey: .thumb)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedExternal_View: Codable, Hashable, Sendable {
        public var external: EmbedExternal_ViewExternal
        public let _unknownValues: [String: AnyCodable]

        public init(external: EmbedExternal_ViewExternal) {
            self.external = external
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case external
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.external = try keyedContainer.decode(EmbedExternal_ViewExternal.self, forKey: .external)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.external, forKey: .external)
            try _unknownValues.encode(to: encoder)
        }
    }

    public struct EmbedExternal_ViewExternal: Codable, Hashable, Sendable {
        public var description: String
        public var thumb: String?
        public var title: String
        public var uri: String
        public let _unknownValues: [String: AnyCodable]

        public init(description: String, thumb: String? = nil, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
            self._unknownValues = [:]
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }

        public init(from decoder: any Decoder) throws {
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            self.description = try keyedContainer.decode(String.self, forKey: .description)
            self.thumb = try keyedContainer.decodeIfPresent(String.self, forKey: .thumb)
            self.title = try keyedContainer.decode(String.self, forKey: .title)
            self.uri = try keyedContainer.decode(String.self, forKey: .uri)
            let unknownContainer = try decoder.container(keyedBy: AnyCodingKeys.self)
            var _unknownValues = [String: AnyCodable]()
            for key in unknownContainer.allKeys {
                guard CodingKeys(rawValue: key.stringValue) == nil else {
                    continue
                }
                _unknownValues[key.stringValue] = try unknownContainer.decode(AnyCodable.self, forKey: key)
            }
            self._unknownValues = _unknownValues
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.description, forKey: .description)
            try container.encodeIfPresent(self.thumb, forKey: .thumb)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.uri, forKey: .uri)
            try _unknownValues.encode(to: encoder)
        }
    }
}
